
services:

  react-to-do_server:
    container_name: react-to-do_server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8110:3001

  react-to-do_web:
    container_name: react-to-do_web
    env_file: ./web/.env
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8010:80
