
services:

  react-to-do_postgres:
    image: postgres:latest
    container_name: react-to-do_postgres
    environment:      
      POSTGRES_DB: react-to-do     
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: postgres
    volumes:    
      - ./server/docker/seed.sql:/docker-entrypoint-initdb.d/seed.sql    
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  
  react-to-do_pgweb: 
    container_name: react-to-do_pgweb
    image: sosedoff/pgweb
    environment: 
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@react-to-do_postgres:5432/react-to-do?sslmode=disable
    ports: 
      - 8081:8081
    depends_on:
      react-to-do_postgres:
        condition: service_healthy

  react-to-do_server:
    container_name: react-to-do_server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8110:3001

  react-to-do_web:
    container_name: react-to-do_web
    env_file: ./web/.env
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8010:80
