# build images during github workflow that pushes (w/ tags) to docker hub
# should only need to push images for postgres, server and web

services:

  react-to-do_postgres:
    container_name: react-to-do_postgres
    build:
      context: ./server
      dockerfile: ./docker/postgres/Dockerfile   

  react-to-do_server:
    image: incerto13/react-to-do_server:${ENV}-latest
    container_name: react-to-do_server
    build:
      context: ./server
      dockerfile: ./docker/server/Dockerfile

  react-to-do_web:
    image: incerto13/react-to-do_web:${ENV}-latest
    container_name: react-to-do_web
    build:
      context: ./web
      dockerfile: ./docker/Dockerfile


