
services:
  frontend:
    container_name: web
    restart: unless-stopped
    env_file: ./web/.env
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    links:
      - backend

  backend:
    container_name: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8110:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
