
services:
  web:
    container_name: web
    environment:
      ENV: ${ENV}
    image: incerto13/react-to-do_web:${ENV}-latest
    restart: unless-stopped
    env_file: ./web/.env
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8010:80

  server:
    container_name: server
    environment:
      ENV: ${ENV}
    image: incerto13/react-to-do_server:${ENV}-latest
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8110:3001
    # volumes:
    #   - ./server:/usr/src/app
    #   - /usr/src/app/node_modules
